/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import static java.util.Collections.list;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.util.List;

/**
 *
 * @author TagoKG
 */
public class AsigPerfilUsuario extends javax.swing.JInternalFrame {
DefaultListModel list = new DefaultListModel();
 DefaultListModel list1 = new DefaultListModel();
    /**
     * Creates new form AsigPerfilUsuario
     */
    public AsigPerfilUsuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Perfiles_A_Aplicaciones = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Quitar_Todos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_cod_Usuario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btn_todos_perfiles_a_Aplicaciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btn_Quitar_uno = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cod_Usuario1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        btn_Quitar_Todos1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        btn_todos_perfiles_a_Aplicaciones1 = new javax.swing.JButton();
        btn_guardar2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        btn_Quitar_uno1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btn_Perfiles_A_Aplicaciones1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        btn_Perfiles_A_Aplicaciones.setText(">");
        btn_Perfiles_A_Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Perfiles_A_AplicacionesActionPerformed(evt);
            }
        });

        jLabel6.setText("asignar");

        jLabel7.setText("aplicaciones asignadas");

        btn_Quitar_Todos.setText("<<");
        btn_Quitar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_TodosActionPerformed(evt);
            }
        });

        jButton1.setText("editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");

        txt_cod_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_UsuarioActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Aplicaciones Disponibles");

        btn_todos_perfiles_a_Aplicaciones.setText(">>");
        btn_todos_perfiles_a_Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todos_perfiles_a_AplicacionesActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        btn_Quitar_uno.setText("<");
        btn_Quitar_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_unoActionPerformed(evt);
            }
        });

        jLabel5.setText("Quitar");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel8.setText("asignar");

        txt_cod_Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_Usuario1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuarios Disponibles:");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList3);

        btn_Quitar_Todos1.setText("<<");
        btn_Quitar_Todos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_Todos1ActionPerformed(evt);
            }
        });

        jButton4.setText("editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Perfiles Disponibles:");

        txt_nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre1ActionPerformed(evt);
            }
        });

        btn_todos_perfiles_a_Aplicaciones1.setText(">>");
        btn_todos_perfiles_a_Aplicaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todos_perfiles_a_Aplicaciones1ActionPerformed(evt);
            }
        });

        btn_guardar2.setText("Guardar");
        btn_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar2ActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jList4);

        btn_Quitar_uno1.setText("<");
        btn_Quitar_uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_uno1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Quitar");

        btn_Perfiles_A_Aplicaciones1.setText(">");
        btn_Perfiles_A_Aplicaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Perfiles_A_Aplicaciones1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(txt_cod_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardar2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(btn_Perfiles_A_Aplicaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_todos_perfiles_a_Aplicaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(btn_Quitar_uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Quitar_Todos1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cod_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Perfiles_A_Aplicaciones1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_todos_perfiles_a_Aplicaciones1)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Quitar_uno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Quitar_Todos1)
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btn_guardar2)
                            .addComponent(jButton2))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Perfiles_A_AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Perfiles_A_AplicacionesActionPerformed

    }//GEN-LAST:event_btn_Perfiles_A_AplicacionesActionPerformed

    private void btn_Quitar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_TodosActionPerformed
        DefaultListModel listModel = (DefaultListModel) jList2.getModel();

        listModel.removeAllElements();
        jList2.setModel(listModel);
    }//GEN-LAST:event_btn_Quitar_TodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cod_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_UsuarioActionPerformed

    private void btn_todos_perfiles_a_AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todos_perfiles_a_AplicacionesActionPerformed

    }//GEN-LAST:event_btn_todos_perfiles_a_AplicacionesActionPerformed

    private void btn_Quitar_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_unoActionPerformed
        /*
        String cadena;
        cadena = (String) jList2.getSelectedValue();

        list.addElement(cadena);
        jList1.setModel(list);
        */
    }//GEN-LAST:event_btn_Quitar_unoActionPerformed

    private void txt_cod_Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_Usuario1ActionPerformed

    private void btn_Quitar_Todos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_Todos1ActionPerformed
        DefaultListModel listModel = (DefaultListModel) jList2.getModel();

        listModel.removeAllElements();
        jList2.setModel(listModel);
    }//GEN-LAST:event_btn_Quitar_Todos1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre1ActionPerformed

    private void btn_todos_perfiles_a_Aplicaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todos_perfiles_a_Aplicaciones1ActionPerformed
        ListModel modelo1= jList1.getModel();// listModel es un objeto y lo que hace es obtener la informacion: list va obtener el modelo del objeto jlist

        for (int i=0; i<modelo1.getSize(); i++){//getSize se obtiene el total de los elementos
            list.addElement(modelo1.getElementAt(i));//añada los elementos conforme el ciclo va avanzando
        }
        jList2.setModel(list);//al segundo jList le setiamos los elementos de list
    }//GEN-LAST:event_btn_todos_perfiles_a_Aplicaciones1ActionPerformed

    private void btn_Quitar_uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_uno1ActionPerformed
        /*
        String cadena;
        cadena = (String) jList2.getSelectedValue();

        list.addElement(cadena);
        jList1.setModel(list);
        */
        list.remove(jList2.getSelectedIndex());
        jList2.setModel(list);
    }//GEN-LAST:event_btn_Quitar_uno1ActionPerformed

    private void btn_Perfiles_A_Aplicaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Perfiles_A_Aplicaciones1ActionPerformed
        String cadena;
        cadena = (String) jList1.getSelectedValue();

       list.addElement(cadena);
        jList2.setModel(list);
    }//GEN-LAST:event_btn_Perfiles_A_Aplicaciones1ActionPerformed

    private void btn_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Perfiles_A_Aplicaciones;
    private javax.swing.JButton btn_Perfiles_A_Aplicaciones1;
    private javax.swing.JButton btn_Quitar_Todos;
    private javax.swing.JButton btn_Quitar_Todos1;
    private javax.swing.JButton btn_Quitar_uno;
    private javax.swing.JButton btn_Quitar_uno1;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar2;
    private javax.swing.JButton btn_todos_perfiles_a_Aplicaciones;
    private javax.swing.JButton btn_todos_perfiles_a_Aplicaciones1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> txt_cod_Usuario;
    private javax.swing.JComboBox<String> txt_cod_Usuario1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    // End of variables declaration//GEN-END:variables
}
